# Generated by Django 2.0 on 2018-01-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20180108_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='work_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='thoughts',
            field=models.TextField(blank=True, default=''),
        ),
    ]
