# Generated by Django 2.0 on 2018-01-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20180110_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_day',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_round',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
